require: rubocop/cop/github

# These cops are compatible across supported versions of rubocop

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/EndAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EndInMethod:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FlipFlop:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/RandOne:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/RedundantSplatExpansion:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/Void:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/MethodName:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: false

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/RangeInclude:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Performance/RedundantMerge:
  Enabled: true
  MaxKeyValuePairs: 1

Performance/ReverseEach:
  Enabled: true

Performance/Size:
  Enabled: true

Performance/StartWith:
  Enabled: true

Security/Eval:
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/CharacterLiteral:
  Enabled: true

Style/ClassMethods:
  Enabled: true

Style/Copyright:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/For:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/LambdaCall:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/Not:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Style/Sample:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/Strip:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
